
# tap repositories and their packages

tap homebrew/cask-versions
cask temurin11
cask temurin17
cask temurin8

tap kubescape/tap

tap minamijoyo/hcledit
brew hcledit

tap rcmdnk/file
brew brew-file

# Other Homebrew packages
brew abseil
brew aom
brew aribb24
brew asdf
brew autoconf
brew automake
brew bdw-gc
brew bonnie++
brew brotli
brew bzip2
brew c-ares
brew ca-certificates
brew cairo
brew capstone
brew cffi
brew cfitsio
brew checkov
brew cjson
brew cmake
brew cmocka
brew coreutils
brew curl
brew dav1d
brew dep
brew diff-so-fancy
brew diffutils
brew direnv
brew dive
brew docker-slim
brew docutils
brew dtc
brew epsilon
brew expat
brew ffmpeg
brew findutils
brew flac
brew fontconfig
brew freetype
brew freexl
brew frei0r
brew fribidi
brew gawk
brew gcc
brew gdbm
brew geos
brew gettext
brew gflags
brew giflib
brew git-extras
brew git-lfs
brew git-secret
brew glib
brew glog
brew gmp
brew gnu-getopt
brew gnu-sed
brew gnu-tar
brew gnu-time
brew gnupg
brew gnupg@2.2
brew gnutls
brew go
brew go-jsonnet
brew graphite2
brew grep
brew grpc
brew guile
brew hadolint
brew harfbuzz
brew hdf5
brew highway
brew hub
brew icu4c
brew imath
brew infracost
brew isl
brew jpeg-turbo
brew jpeg-xl
brew jq
brew json-c
brew jsoncpp
brew krb5
brew lame
brew leptonica
brew less
brew libaec
brew libarchive
brew libass
brew libassuan
brew libb2
brew libbluray
brew libdap
brew libde265
brew libevent
brew libffi
brew libgcrypt
brew libgeotiff
brew libgpg-error
brew libheif
brew libidn2
brew libksba
brew libmpc
brew libnghttp2
brew libogg
brew libpng
brew libpq
brew libpthread-stubs
brew librist
brew librttopo
brew libsamplerate
brew libslirp
brew libsndfile
brew libsodium
brew libsoxr
brew libspatialite
brew libssh
brew libssh2
brew libtasn1
brew libtermkey
brew libtiff
brew libtool
brew libunibreak
brew libunistring
brew libusb
brew libuv
brew libvidstab
brew libvmaf
brew libvorbis
brew libvpx
brew libvterm
brew libx11
brew libxau
brew libxcb
brew libxdmcp
brew libxext
brew libxml2
brew libxrender
brew libyaml
brew little-cms2
brew lpeg
brew lua
brew luajit
brew luajit-openresty
brew luarocks
brew luv
brew lz4
brew lzo
brew m4
brew make
brew mas
brew mbedtls
brew minizip
brew mpdecimal
brew mpfr
brew mpg123
brew msgpack
brew ncdu
brew ncurses
brew netcdf
brew nettle
brew node
brew npth
brew nspr
brew nss
brew numpy
brew oniguruma
brew openblas
brew opencore-amr
brew openexr
brew openjpeg
brew openldap
brew openssl@1.1
brew openssl@3
brew opus
brew p11-kit
brew pango
brew pcre
brew pcre2
brew pinentry
brew pipx
brew pixman
brew pkg-config
brew poppler
brew popt
brew pre-commit
brew prettier
brew proj
brew protobuf
brew pycparser
brew python-build
brew python-certifi
brew python-markdown
brew python-packaging
brew python-pyproject-hooks
brew python-tabulate
brew python-tk@3.10
brew python-tk@3.9
brew python-typing-extensions
brew python@3.10
brew python@3.11
brew python@3.9
brew pyyaml
brew qemu
brew rapidjson
brew rav1e
brew re2
brew readline
brew ripgrep
brew rsync
brew rtmpdump
brew rubberband
brew ruby-build
brew sdl2
brew shared-mime-info
brew shellcheck
brew six
brew snappy
brew speex
brew sqlite
brew srt
brew ssh-copy-id
brew stern
brew svt-av1
brew tcl-tk
brew terraform-docs
brew terrascan
brew tesseract
brew tfenv
brew tflint
brew tfsec
brew tfupdate
brew theora
brew thrift
brew tree
brew tree-sitter
brew unbound
brew unibilium
brew unixodbc
brew utf8proc
brew vde
brew virtualenv
brew webp
brew wget
brew x264
brew x265
brew xerces-c
brew xorgproto
brew xvid
brew xxhash
brew xz
brew yq
brew z3
brew zeromq
brew zimg
brew zlib
brew zsh
brew zsh-completions
brew zstd

# Other Cask applications
cask 1password
cask ableton-live-suite
cask appcleaner
cask c0re100-qbittorrent
cask diffmerge
cask discord
cask disk-inventory-x
cask expressvpn
cask firefox
cask google-chrome
cask google-cloud-sdk
cask iina
cask iterm2
cask orbstack
cask ripx
cask skim
cask spotify
cask steam
cask tor-browser
cask visual-studio-code
cask vlc
cask zoom

# App Store applications
appstore 1569813296  1Password for Safari  (2.15.1)
appstore 1432731683  Adblock Plus          (2.2.9)
appstore 937984704   Amphetamine           (5.3)
appstore 975937182   Fantastical           (3.7.21)
appstore 1460836908  GoPro Player          (2.1.9)
appstore 409183694   Keynote               (13.1)
appstore 409203825   Numbers               (13.1)
appstore 429449079   Patterns              (1.3)
appstore 1472777122  PayPal Honey          (16.1.6)
appstore 545519333   Prime Video           (10.4.1)
appstore 803453959   Slack                 (4.34.119)
appstore 747648890   Telegram              (10.0.5)
appstore 1147396723  WhatsApp              (2.2336.9)
appstore 497799835   Xcode                 (15.0)
