
# tap repositories and their packages

tap homebrew/core
brew aom
brew asdf
brew autoconf
brew automake
brew awscli
brew bdw-gc
brew bonnie++
brew brotli
brew c-ares
brew ca-certificates
brew cairo
brew checkov
brew cjson
brew cmake
brew cmocka
brew coreutils
brew curl
brew dav1d
brew dep
brew diff-so-fancy
brew direnv
brew docker-slim
brew ffmpeg
brew findutils
brew flac
brew fontconfig
brew freetype
brew frei0r
brew fribidi
brew gawk
brew gdbm
brew gettext
brew giflib
brew git-extras
brew git-lfs
brew glib
brew gmp
brew gnu-getopt
brew gnu-sed
brew gnu-tar
brew gnupg@2.2
brew gnutls
brew go
brew go-jsonnet
brew graphite2
brew grep
brew guile
brew hadolint
brew harfbuzz
brew highway
brew icu4c
brew imath
brew infracost
brew jmeter
brew jpeg-turbo
brew jpeg-xl
brew jq
brew lame
brew leptonica
brew less
brew libarchive
brew libass
brew libassuan
brew libb2
brew libbluray
brew libevent
brew libffi
brew libgcrypt
brew libgpg-error
brew libidn2
brew libksba
brew libnghttp2
brew libogg
brew libpng
brew libpthread-stubs
brew libpython-tabulate
brew librist
brew libsamplerate
brew libsndfile
brew libsodium
brew libsoxr
brew libssh2
brew libtasn1
brew libtermkey
brew libtiff
brew libtool
brew libunistring
brew libusb
brew libuv
brew libvidstab
brew libvmaf
brew libvorbis
brew libvpx
brew libvterm
brew libx11
brew libxau
brew libxcb
brew libxdmcp
brew libxext
brew libxrender
brew libyaml
brew little-cms2
brew lua
brew luajit
brew luajit-openresty
brew luarocks
brew luv
brew lz4
brew lzo
brew m4
brew make
brew mas
brew mbedtls
brew mpdecimal
brew mpfr
brew msgpack
brew ncurses
brew neovim --HEAD
brew nettle
brew node
brew npth
brew oniguruma
brew opencore-amr
brew openexr
brew openjdk
brew openjdk@11
brew openjpeg
brew openldap
brew openssl@1.1
brew openssl@3
brew opus
brew p11-kit
brew pcre
brew pcre2
brew pinentry
brew pixman
brew pkg-config
brew popt
brew pre-commit
brew python-tk@3.10
brew python-tk@3.9
brew python-typing-extensions
brew python@3.10
brew python@3.9
brew pyyaml
brew rav1e
brew readline
brew ripgrep
brew rsync
brew rtmpdump
brew rubberband
brew ruby-build
brew sdl2
brew shellcheck
brew six
brew snappy
brew speex
brew sqlite
brew srt
brew ssh-copy-id
brew stern
brew tcl-tk
brew terraform-docs
brew terrascan
brew tesseract
brew tfenv
brew tflint
brew tfsec
brew tfupdate
brew theora
brew tree
brew tree-sitter
brew unbound
brew unibilium
brew unixodbc
brew webp
brew wget
brew x264
brew x265
brew xorgproto
brew xvid
brew xxhash
brew xz
brew yq
brew zeromq
brew zimg
brew zsh
brew zsh-completions
brew zstd

tap homebrew/cask
cask 1password
cask appcleaner
cask diffmerge
cask docker
cask expressvpn
cask firefox
cask gifox
cask google-chrome
cask google-cloud-sdk
cask iterm2
cask keybase
cask qbittorrent
cask spotify
cask visual-studio-code
cask vlc
cask zoom

tap adoptopenjdk/openjdk

tap danvergara/tools
brew dblab

tap minamijoyo/hcledit
brew hcledit

tap rcmdnk/file
brew brew-file

# App Store applications
appstore 1569813296  1Password for Safari  (2.3.7)
appstore 937984704   Amphetamine           (5.2.2)
appstore 975937182   Fantastical           (3.6.6)
appstore 1460836908  GoPro Player          (2.0.9)
appstore 409183694   Keynote               (12.1)
appstore 409203825   Numbers               (12.1)
appstore 429449079   Patterns              (1.2)
appstore 803453959   Slack                 (4.27.154)
