
# tap repositories and their packages

## Direct install
brew neovim

tap kubescape/tap

tap rcmdnk/file
brew brew-file

# Other Homebrew packages
brew abseil
brew aom
brew aribb24
brew asdf
brew autoconf
brew automake
brew bash
brew bdw-gc
brew bonnie++
brew brotli
brew bzip2
brew c-ares
brew ca-certificates
brew cairo
brew capstone
brew certifi
brew cffi
brew cfitsio
brew checkov
brew cjson
brew cmake
brew cmocka
brew coreutils
brew curl
brew dav1d
brew diff-so-fancy
brew diffutils
brew direnv
brew dive
brew docutils
brew dos2unix
brew dtc
brew dyff
brew epsilon
brew expat
brew eza
brew fd
brew ffmpeg
brew findutils
brew flac
brew fontconfig
brew freetype
brew freexl
brew frei0r
brew fribidi
brew fzf
brew gawk
brew gcc
brew gdbm
brew geos
brew gettext
brew gflags
brew gh
brew giflib
brew git-extras
brew git-lfs
brew git-secret
brew glib
brew glog
brew gmp
brew gnu-getopt
brew gnu-sed
brew gnu-tar
brew gnu-time
brew gnupg
brew gnutls
brew go
brew gpgme
brew graphite2
brew grep
brew grpc
brew guile
brew hadolint
brew harfbuzz
brew hcledit
brew hdf5
brew highway
brew hub
brew icu4c@77
brew imath
brew infracost
brew isl
brew jpeg-turbo
brew jpeg-xl
brew jq
brew jrsonnet
brew json-c
brew krb5
brew lame
brew leptonica
brew less
brew libaec
brew libarchive
brew libass
brew libassuan
brew libb2
brew libbluray
brew libde265
brew libdeflate
brew libevent
brew libffi
brew libgcrypt
brew libgeotiff
brew libgit2
brew libgpg-error
brew libheif
brew libidn2
brew libksba
brew libmicrohttpd
brew libmpc
brew libnghttp2
brew libogg
brew libpng
brew libpq
brew libpthread-stubs
brew librist
brew librttopo
brew libsamplerate
brew libslirp
brew libsndfile
brew libsodium
brew libsoxr
brew libspatialite
brew libssh
brew libssh2
brew libtasn1
brew libtermkey
brew libtiff
brew libtommath
brew libtool
brew libunibreak
brew libunistring
brew libusb
brew libuv
brew libvidstab
brew libvmaf
brew libvorbis
brew libvpx
brew libvterm
brew libx11
brew libxau
brew libxcb
brew libxdmcp
brew libxext
brew libxml2
brew libxrender
brew libyaml
brew little-cms2
brew lpeg
brew lua
brew luajit
brew luajit-openresty
brew luarocks
brew luv
brew lz4
brew lzo
brew m4
brew make
brew mas
brew mbedtls
brew minizip
brew mintoolkit
brew mkcert
brew mpdecimal
brew mpfr
brew mpg123
brew msgpack
brew ncdu
brew ncurses
brew netcdf
brew nettle
brew node
brew npth
brew nspr
brew nss
brew numpy
brew oniguruma
brew openblas
brew opencore-amr
brew openexr
brew openjpeg
brew openldap
brew openssl@3
brew operator-sdk
brew opus
brew p11-kit
brew pandoc
brew pango
brew pcre
brew pcre2
brew pinentry
brew pinentry-mac
brew pipx
brew pixman
brew pkgconf
brew poetry
brew poppler
brew popt
brew pre-commit
brew prettier
brew proj
brew protobuf
brew pycparser
brew python-packaging
brew python-tabulate
brew python-tk@3.10
brew python-tk@3.9
brew python@3.10
brew python@3.11
brew python@3.12
brew python@3.13
brew python@3.9
brew qemu
brew rapidjson
brew rav1e
brew re2
brew readline
brew redis@6.2
brew ripgrep
brew rsync
brew rtmpdump
brew rubberband
brew ruby-build
brew sdl2
brew shared-mime-info
brew shellcheck
brew six
brew sloth
brew smartmontools
brew snappy
brew speex
brew sqlite
brew srt
brew ssh-copy-id
brew starship
brew stern
brew svt-av1
brew tcl-tk
brew tcl-tk@8
brew terraform-docs
brew terrascan
brew tesseract
brew tfenv
brew tflint
brew tfsec
brew tfupdate
brew theora
brew thrift
brew tree
brew tree-sitter
brew unbound
brew unibilium
brew unixodbc
brew utf8proc
brew vde
brew virtualenv
brew webp
brew wget
brew x264
brew x265
brew xerces-c
brew xorgproto
brew xvid
brew xxhash
brew xz
brew yq
brew z3
brew zeromq
brew zimg
brew zlib
brew zplug
brew zsh-completions
brew zstd

# Other Cask applications
cask 1password
cask appcleaner
cask basictex
cask c0re100-qbittorrent
cask chatgpt
cask cursor
cask diffmerge
cask discord
cask disk-inventory-x
cask expressvpn
cask firefox
cask google-chrome
cask google-cloud-sdk
cask handbrake
cask iina
cask iterm2
cask notion
cask orbstack
cask raspberry-pi-imager
cask ripx
cask skim
cask spotify
cask steam
cask tigervnc-viewer
cask tor-browser
cask visual-studio-code
cask vlc
cask zoom
cask zulu@21

# App Store applications
appstore 1569813296  1Password for Safari  (8.10.70)
appstore 937984704   Amphetamine           (5.3.2)
appstore 975937182   Fantastical           (4.0.10)
appstore 1460836908  GoPro Player          (3.1.0)
appstore 409183694   Keynote               (14.4)
appstore 409203825   Numbers               (14.4)
appstore 490179405   Okta Verify           (9.39.0)
appstore 429449079   Patterns              (1.3)
appstore 545519333   Prime Video           (10.69)
appstore 803453959   Slack                 (4.43.52)
appstore 747648890   Telegram              (11.9)
appstore 310633997   WhatsApp              (25.13.74)
appstore 1147396723  WhatsApp (old)        (2.2437.52)
appstore 1295203466  Windows App           (11.1.4)
appstore 497799835   Xcode                 (16.3)
